name: Simple Manual Workflow

#Controls when action will run
on:
  #Allows you to run this workflow manually from the actions tab
  workflow_dispatch:

# A workflow run is made up of ine or morejobs that can run sequentially or in parallel
jobs:
  DEV:
    # the type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: DEV

    # steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run a script
        run: |
          echo "I am running a job in the DEV environment"

  QA:
    runs-on: ubuntu-latest
    environment: QA
    needs: DEV

    steps:
      - uses: actions/checkout@v2
      - name: Run a script
        run: |
          echo "I am running a job in the QA environment"
        
  PROD:
    runs-on: ubuntu-lates
    environment: PROD
    needs: QA
    steps:
      - uses: action/checkout@v2
      - name: Run a script
        run: |
          echo "I am running a job in the PROD environment"
 
